global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fraud-detection'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    metrics_path: '/metrics'

  - job_name: 'fraud-predictor'
    static_configs:
      - targets: ['fraud-predictor:8000']
    metrics_path: '/metrics'
